void MainMenu();
void MainMenu();
void PlayGame();
void HowToPlay();
void AboutAuthor();
void GeneratteDeck();
void Bets(bool);
void AddCard(bool);
void BotTurn();
void CalculateScore(bool);
void ShowCard(COORD& CardPosition, int value, int suit, int i, bool);
void SetCursor(COORD& position, int x, int y);
void Nyuta();
void Stepa();
void SetUpCard();
void EndOfGame(bool defeat, bool bot, int& bank);
void BackOrNext(COORD& Position, int margin, int count);
void WindowsHowToPlay(int count);
void ShowWindowsHowToPlay(COORD Position, const int current_item, string(&items)[2], int margin, int count);
int GetCardStatuses(bool Value, int PosistionInDeck);
void Table();
void ShowBackCard(COORD& CardPosition, int X, int Y);